name: Build MSI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download WiX Toolset
      run: |
        curl -L -o wix311-binaries.zip https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
        mkdir wix
        Expand-Archive -Path wix311-binaries.zip -DestinationPath wix

    - name: Build MSI
      run: |
        cd installer
        ..\wix\candle.exe pathetic-lang.wxs -ext WixUIExtension
        ..\wix\light.exe pathetic-lang.wixobj -ext WixUIExtension -out pathetic-lang.msi
      shell: cmd

    - name: Upload MSI
      uses: actions/upload-artifact@v4
      with:
        name: pathetic-lang-msi
        path: installer/pathetic-lang.msi